first_name: "Soham"
last_name: "Biswas"
birth_year: 1999
bg_image: "/assets/images/cc-bg-1.jpg"
profile_pic: "/assets/images/profile_pic.jpg"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag